agro_planning_farm:
    resource: "@AgroPlanningFarmBundle/Controller"
    prefix:   /admin
    type: annotation

agro_planning_vehicle:
    resource: "@AgroPlanningVehicleBundle/Controller"
    prefix:   /admin/{_locale}
    type: annotation

agro_planning_dashboard:
    resource: "@AgroPlanningDashboardBundle/Resources/config/routing.yml"
    prefix:   /admin/{_locale}

agro_planning_tag:
    resource: "@AgroPlanningTagBundle/Controller/"
    prefix: /admin/{_locale}
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
