AgroPlanning\TagBundle\Entity\Tag:
    type: entity
    table: tag
    repositoryClass: AgroPlanning\TagBundle\Entity\TagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        colour:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
